# Generated by Django 5.0.6 on 2024-06-09 12:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0002_business_profile_pic_freelancer_profile_pic"),
    ]

    operations = [
        migrations.AddField(
            model_name="business",
            name="Email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="business",
            name="Phone_number",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="business",
            name="Reviews",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="freelancer",
            name="Email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="freelancer",
            name="Phone_number",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="freelancer",
            name="Reviews",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="freelancer",
            name="Skills",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
